#!/bin/bash
# Show information about files worked on for a set of commits
#   (specifically, create a sorted list of files that were affected by a
#    set of commits)
#
# This is useful for checking what a particular author has been
# working on lately (through the whole tree).  Use git log <dir>
# to see what authors have been working in a particular dir.
#

# uncomment the next line to debug this script
#set -x

KERNEL_SRC=/home/tbird/work/torvalds/linux

usage() {
cat <<HERE
Usage: files-worked-on <options> <scope-args>

List the files worked on in a git repository, for commits
that match the specified scope arguments.  The scope
arguments are passed to 'git log', and are usually
something like --author= and --since=

 Some common scope args types are:
   arch/arm64         - get files worked on by commits in the arch/arm64 dir
   --author="*sony*"  - get files worked on by Sony developers
   --since=2023-04-01 - get files worked on since April 1, 2023
   v3.4..             - get files worked on since the v3.4 tag

Output is in diffstat format

Note that this uses environment var GIT_SCOPE, if defined

Example:
files-worked-on --author=tim.bird --since=2024-01-01

Options:
 -h        Show this usage help
 -k <dir>  Use <dir> as the kernel source dir.  Otherwise, this
           script tries to autodetect it.
 -f        Force using the current directory, instead of autodetecting
           the default (which is: '$KERNEL_SRC').
HERE
}

if [ "$1" = "-h" ] ; then
    usage
    exit 0
fi

if [ "$1" = "-k" ] ; then
    shift
    KERNEL_SRC="$1"
    shift
    pushd $KERNEL_SRC >/dev/null
    DID_PUSHD=1
fi

CHECK_DIR=1
if [ "$1" = "-f" ] ; then
    shift
    CHECK_DIR=
fi

if [ -n "$CHECK_DIR" ] ; then
    if [ ! -e MAINTAINERS ] ; then
        echo "Not at root of kernel source tree, using default"
        echo "KERNEL_SRC=$KERNEL_SRC"
        pushd $KERNEL_SRC >/dev/null
        DID_PUSHD=1
    fi
fi

SCOPE="$GIT_SCOPE $@"
if [ -n "$SCOPE" ] ; then
    echo "SCOPE=$SCOPE"
fi
COMMIT_LIST=$(git log --all-match --pretty=%h -i $SCOPE)

COMMIT_COUNT=$(echo $COMMIT_LIST | wc -w)
echo "Number of commits = $COMMIT_COUNT"

TMPFILE=$(mktemp)
for COMMIT in $COMMIT_LIST ; do
    git show $COMMIT | diffstat -p 0 | head -n-1 >>$TMPFILE
done

# remove leading ' b/'
cat $TMPFILE | sed "s#^ b/##" | sort
rm $TMPFILE

if [ -n "$DID_PUSHD" ] ; then
    popd >/dev/null
fi
