#!/usr/bin/python
# SPDX-License-Identifier: MIT
#
# Copyright 2026 Sony Group Corporation
#
# guess-license - examine a file, and guess it's license based on
#
# to do:
# - phase 1
#    - test BSD-Source-Code license matching
# - phase 2
#    - scan surrounding files, and use a matching license
#    - use an ID that is common for that file (GPL-2.0?)

# NOTES:
#  - BSD-2-Clause is tricky, because it's very similar to 3-Clause, just
#    missing some stuff.
#  - order of comparison matters

import sys
import os
import re

debug = False

lic_list = []
gpl_list = []
bsd_list = []

def usage():
    print("""Usage: guess-license [options] <file> [file2..]

Scan each specified file for license text, and report an SPDX ID
that matches the license text (if found).

Options:
 -h      Show this usage help
 --debug Show debug information
""")
    sys.exit(0)

GPL_header_text = """
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, see <https://www.gnu.org/licenses/>.
"""

BSD2_Clause_text = """
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
"""

BSD3_Clause_text = """
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
"""

BSD3_Clause_Clear_text = """
Redistribution and use in source and binary forms, with or without
modification, are permitted (subject to the limitations in the disclaimer
below) provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

 * Neither the name of [Owner Organization] nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

BSD_Source_Code_text="""
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 - Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer,
   without modification.

 - The name of the author may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
"""

MIT_text="""
Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
"""

def dprint(msg):
    global debug

    if debug:
        print("DEBUG: " + msg)

# lic_list is a list of tuples with (id, re_start, re_end, text)
class license_class():
    def __init__(self, lic_id, re_start, re_end, text):
        self.id = lic_id
        self.re_start = re.compile(re_start)
        self.re_end = re.compile(re_end)
        self.text = text

def init_license_lists():
    global lic_list, gpl_list, bsd_list

    lic_list = []
    gpl_list = []
    bsd_list = []
    lic_list.append(license_class("GPL",
        "terms of the GNU General Public License",
        "GNU General Public License for more details",
        ""))
    gpl_list.append(license_class("GPL-2.0",
        "version 2",
        "",
         GPL_header_text))
    gpl_list.append(license_class("GPL-2.0+",
        "any later version",
        "",
         GPL_header_text))

    lic_list.append(license_class("BSD",
        "Redistributions and use in source and binary forms",
        "",
        ""))
    bsd_list.append(license_class("BSD-2-Clause",
        "Redistributions in binary form must reproduce",
        "",
        BSD2_Clause_text))
    bsd_list.append(license_class("BSD-3-Clause",
        "Neither the name of the copyright holder nor the names.*without specific prior written permission",
        "",
        BSD3_Clause_text))
    bsd_list.append(license_class("BSD-3-Clause-Clear",
        "Neither the name of.*used to endorse or promote.*without specific prior written permission",
        "",
        BSD3_Clause_Clear_text))
    bsd_list.append(license_class("BSD-Source-Code",
        "name of the author.*endorse or promote.*without specific prior written permission",
        "",
        BSD_Source_Code_text))

    lic_list.append(license_class("MIT",
        "Permission to use, copy, modify.*distribute.*is hereby granted",
        "",
        MIT_text))


def main():
    global debug

    if "-h" in sys.argv:
        usage()
    if "--debug" in sys.argv:
        debug = True
        sys.argv.remove("--debug")

    if len(sys.argv)<2:
        print("Error: missing file to scan. Use -h for help")
        sys.exit(1)

    filepaths = sys.argv[1:]

    init_license_lists()

    for filepath in filepaths:
        if not os.path.isfile(filepath):
            print("Error: '%s' is not a file. Use -h for  help" % filepath)
            continue

        f = open(filepath, "r")

        header_text = ""
        found = False
        for i in range(50):
            line = f.readline().strip()
            if "SPDX-License-Identifier:" in line:
                spdx_id = line.split(":",1)[1].strip()
                print("%s: already has SPDX id: %s" % (filepath, spdx_id))
                found = True
                break

            dprint("line='%s'" % line)
            if line.startswith("/*"):
                line = line[2:].strip()
            if line.startswith("* "):
                line = line[2:].strip()
            if line.startswith("/* "):
                line = line[3:].strip()
            if line.startswith("/** "):
                line = line[4:].strip()
            if line.endswith("*/"):
                line = line[:-2]
            if line.startswith("*"):
                line = line[1:].strip()
            dprint("line='%s'" % line)
            if line:
                header_text += (" " + line)
            dprint("header_text='%s'" % header_text)

        if found:
            continue

        guess_list = []
        for lic in lic_list:
            lic_id = ""
            dprint("checking license %s" % lic.id)
            if lic.re_start.search(header_text):
                lic_id = lic.id
                if lic_id == "GPL":
                    for gpl_lic in gpl_list:
                       if gpl_lic.re_start.search(header_text):
                           lic_id = gpl_lic.id
                if lic_id == "BSD":
                    for bsd_lic in bsd_list:
                       if bsd_lic.re_start.search(header_text):
                           lic_id = gpl_lic.id

            if lic_id:
                guess_list.append(lic_id)
            dprint("guess_list=%s" % guess_list)

        if len(guess_list) == 0:
            lic_id = "no license text found: use GPL-2.0"
        elif len(guess_list) == 1:
            lic_id = guess_list[0]
        elif len(guess_list) > 1:
            or_list = " OR ".join(guess_list)
            lic_id = "complex: maybe %s" % or_list

        print("%s: %s" % (filepath, lic_id))
        if lic_id.startswith("unknown"):
            dprint("Here is some data:\n== Header text ==")
            dprint(header_text)
            dprint("== Match data ==")
            dprint("Permission to use")
            dprint(re.search("Permission to use", header_text))

if __name__ == "__main__":
    main()
